### ISSUE TITLE
[バグ] main がコンパイルできない: WorkerStatusCtx の input_style が #1295 のテストに無い（#1297 との semantic merge conflict）

### ISSUE THREAD

**Issue by takushio2525** [takushio2525/tako#1339]
`origin/main`（`66c66b2`）で `cargo test -p tako-control --lib` がコンパイルエラーになり、**すべての PR の CI が緑にできない**。

```
error[E0063]: missing field `input_style` in initializer of `dispatch::WorkerStatusCtx`
     --> crates/tako-control/src/dispatch.rs:24164:17
```

## 原因

連続して merge された 2 本の **semantic merge conflict**。どちらも単体では緑だった。

- `20b7420`（#1297 / PR #1330）が `WorkerStatusCtx` に `input_style: Option<tako_core::InputStyle>` を**追加**した
- `280826d`（#1295 / PR #1329）が `dispatch.rs:24164` に `WorkerStatusCtx` を構築する**テストを追加**した。こちらは追加前のフィールド構成で書かれている

main の CI も `280826d` の時点で failure（`20b7420` は success）。

## 直し方

`crates/tako-control/src/dispatch.rs:24164` の構造体リテラルへ `input_style: None,` を 1 行足す。

- 同ファイルの他の構築箇所（`:17698` / `:17718` / `:17736` / `:17753` / `:17776` / `:17802` ほか）はすべて `input_style: None`
- フィールドの doc コメントが「**None = 属性が取れない**（ペインが GUI に無く素の tmux capture へ落ちた等）」と定義しており、#1295 のテストは画面テキストだけを与える形なので `None` が意味的に正しい（#1297 の判定は従来の文字列判定へ落ちる = #1295 のテストが書かれた前提のまま）

## 再現手順

```bash
git worktree add --detach /tmp/main-check origin/main
cd /tmp/main-check && cargo test -p tako-control --lib --no-run
```

## 影響

PR #1335 / #1334 / #1337 がこの理由で macOS CI に落ちている。

**Comment by takushio2525** [comment]
着手: docs worker（#1317 / #1322 / #1323 = PR #1335）が、自 PR の CI がこれで落ちたため 1 行修正の PR を別途出します（2026-09-11）。docs PR には混ぜません。

**Comment by takushio2525** [comment]
master 側で同じ破損が #1343 として起票されていたので、そちらへ寄せます（修正 PR は #1342 のまま。#1342 は両方を close します）。

**Comment by takushio2525** [comment]
重複: #1343 に統合（修正は PR #1342）
